apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - movies.example.com
      secretName: movies-tls-secret
  rules:
    - host: movies.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movie-app-service
                port:
                  number: 80
